# Generated by Django 3.2.3 on 2021-05-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='authorKey',
            field=models.CharField(default=None, max_length=100, verbose_name='Author username (i.e. rakenaj)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspage',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Author full name (i.e. Jackson Rakena)'),
        ),
    ]
