# Generated by Django 3.2.3 on 2021-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210521_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='show_on_front_page',
            field=models.BooleanField(default=True, verbose_name='Show on front page'),
        ),
    ]
