# Generated by Django 3.2.3 on 2021-05-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_newspage_show_on_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Author full name'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
